function casper_library_downconverter_init()

	warning off Simulink:Engine:MdlFileShadowing;
	close_system('casper_library_downconverter', 0);
	mdl = new_system('casper_library_downconverter', 'Library');
	blk = get(mdl,'Name');
	% Set the EnableLBRepository property to on
	try
	  set_param(mdl, 'EnableLBRepository', 'on');
	catch
	  % ignore
	end
	warning on Simulink:Engine:MdlFileShadowing;

	add_block('built-in/SubSystem', [blk,'/mixer']);
	mixer_gen([blk,'/mixer']);
	set_param([blk,'/mixer'], ...
		'freq_div', sprintf('2'), ...
		'freq', sprintf('2'), ...
		'nstreams', sprintf('0'), ...
		'n_bits', sprintf('4'), ...
		'bram_latency', sprintf('2'), ...
		'mult_latency', sprintf('4'), ...
		'Position', sprintf('[15 30 80 120]'), ...
		'Tag', sprintf('casper:mixer'));

	add_block('built-in/SubSystem', [blk,'/sincos']);
	sincos_gen([blk,'/sincos']);
	set_param([blk,'/sincos'], ...
		'func', sprintf('sine and cosine'), ...
		'neg_sin', sprintf('off'), ...
		'neg_cos', sprintf('off'), ...
		'symmetric', sprintf('on'), ...
		'handle_sync', sprintf('off'), ...
		'depth_bits', sprintf('0'), ...
		'bit_width', sprintf('16'), ...
		'bram_latency', sprintf('2'), ...
		'Position', sprintf('[102 26 157 64]'), ...
		'Tag', sprintf('casper:sincos'));

	add_block('built-in/SubSystem', [blk,'/feedback_osc']);
	feedback_osc_gen([blk,'/feedback_osc']);
	set_param([blk,'/feedback_osc'], ...
		'n_bits', sprintf('0'), ...
		'n_bits_rotation', sprintf('25'), ...
		'phase_initial', sprintf('0'), ...
		'phase_step_bits', sprintf('8'), ...
		'phase_steps_bits', sprintf('8'), ...
		'ref_values_bits', sprintf('1'), ...
		'bram_latency', sprintf('2'), ...
		'mult_latency', sprintf('2'), ...
		'add_latency', sprintf('1'), ...
		'conv_latency', sprintf('2'), ...
		'bram', sprintf('Distributed memory'), ...
		'quantization', sprintf('Round  (unbiased: Even Values)'), ...
		'Position', sprintf('[105 101 145 139]'), ...
		'Tag', sprintf('casper:feedback_osc'));

	add_block('built-in/SubSystem', [blk,'/cosin']);
	cosin_gen([blk,'/cosin']);
	set_param([blk,'/cosin'], ...
		'output0', sprintf('sin'), ...
		'output1', sprintf('cos'), ...
		'indep_theta', sprintf('off'), ...
		'phase', sprintf('0'), ...
		'fraction', sprintf('0'), ...
		'store', sprintf('0'), ...
		'table_bits', sprintf('0'), ...
		'n_bits', sprintf('18'), ...
		'bin_pt', sprintf('17'), ...
		'bram_latency', sprintf('1'), ...
		'add_latency', sprintf('1'), ...
		'mux_latency', sprintf('1'), ...
		'neg_latency', sprintf('1')